export type FieldDef = {
  key: string;
  label: string;
  type: "text" | "textarea" | "array" | "entity_source";
  sourceEntityTypes?: string[];
};

export type EntityConfig = {
  type: string;
  label: string;
  labelPlural: string;
  color: string;       // Tailwind bg class for dot + badge bg
  textColor: string;   // Tailwind text class for badge
  hex: string;         // raw hex for inline use
  fields: FieldDef[];
};

export const ENTITY_CONFIGS: EntityConfig[] = [
  {
    type: "affiliations",
    label: "Affiliation",
    labelPlural: "Affiliations",
    color: "bg-[#8E5B6E]",
    textColor: "text-[#FEFEFA]",
    hex: "#8E5B6E",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "clinical_identifiers", label: "Clinical Identifiers", type: "textarea" },
      { key: "review_date", label: "Review Date", type: "text" },
      { key: "cost", label: "Cost", type: "text" },
      { key: "source", label: "Source", type: "entity_source", sourceEntityTypes: ["vendors"] },
      { key: "benefits", label: "Benefits", type: "textarea" },
      { key: "links", label: "Links", type: "textarea" },
      { key: "education", label: "Education", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "amino_acids",
    label: "Amino Acid",
    labelPlural: "Amino Acids",
    color: "bg-[#C4A882]",
    textColor: "text-[#272727]",
    hex: "#C4A882",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "role", label: "Role / Function", type: "textarea" },
      { key: "food_sources", label: "Food Sources", type: "textarea" },
      { key: "deficiency_signs", label: "Deficiency Signs", type: "textarea" },
      { key: "normal_range", label: "Normal Range", type: "textarea" },
      { key: "dosage", label: "Supplemental Dosage", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "anatomy_physiology",
    label: "Anatomy & Physiology",
    labelPlural: "Anatomy & Physiology",
    color: "bg-[#8B6FAE]",
    textColor: "text-[#FEFEFA]",
    hex: "#8B6FAE",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "body_system", label: "Body System", type: "text" },
      { key: "structures", label: "Structures", type: "textarea" },
      { key: "function", label: "Function", type: "textarea" },
      { key: "clinical_relevance", label: "Clinical Relevance", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "assessments",
    label: "Assessment",
    labelPlural: "Assessments",
    color: "bg-[#4E7A8C]",
    textColor: "text-[#FEFEFA]",
    hex: "#4E7A8C",
    fields: [
      { key: "assessment_type", label: "Type", type: "text" },
      { key: "purpose", label: "Purpose", type: "textarea" },
      { key: "links", label: "Links", type: "textarea" },
      { key: "citations", label: "Citations", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "biochemical_markers",
    label: "Biomarker",
    labelPlural: "Biomarkers",
    color: "bg-[#272727]",
    textColor: "text-[#FEFEFA]",
    hex: "#272727",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "normal_range", label: "Normal Range", type: "textarea" },
      { key: "low_interpretation", label: "Low Interpretation", type: "textarea" },
      { key: "high_interpretation", label: "High Interpretation", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "ce",
    label: "CE",
    labelPlural: "CE",
    color: "bg-[#D4A24C]",
    textColor: "text-[#272727]",
    hex: "#D4A24C",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "topic", label: "Topic", type: "text" },
      { key: "source", label: "Source", type: "entity_source", sourceEntityTypes: ["laboratories", "vendors"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "diagnoses",
    label: "Diagnosis",
    labelPlural: "Diagnoses",
    color: "bg-[#77ACA2]",
    textColor: "text-[#272727]",
    hex: "#77ACA2",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "icd10_codes", label: "ICD-10 Code(s)", type: "array" },
      { key: "differential_diagnosis", label: "Differential Diagnosis", type: "textarea" },
      { key: "dsm_v", label: "DSM-V", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "equipment",
    label: "Equipment",
    labelPlural: "Equipment",
    color: "bg-[#5C6B73]",
    textColor: "text-[#FEFEFA]",
    hex: "#5C6B73",
    fields: [
      { key: "classification", label: "Classification", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "brand", label: "Brand", type: "text" },
      { key: "source", label: "Source", type: "entity_source", sourceEntityTypes: ["vendors"] },
      { key: "instructions", label: "Instructions", type: "textarea" },
      { key: "accessories", label: "Accessories", type: "array" },
      { key: "maintenance", label: "Maintenance", type: "textarea" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "cost", label: "Cost", type: "text" },
      { key: "faqs", label: "FAQs", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "forms",
    label: "Form",
    labelPlural: "Forms",
    color: "bg-[#7A6C5D]",
    textColor: "text-[#FEFEFA]",
    hex: "#7A6C5D",
    fields: [
      { key: "form_type", label: "Type", type: "text" },
      { key: "purpose", label: "Purpose", type: "textarea" },
      { key: "policy_and_procedure", label: "Policy and Procedure", type: "textarea" },
      { key: "review_date", label: "Review Date", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "genetics",
    label: "Genetic Marker",
    labelPlural: "Genetics",
    color: "bg-[#6B8CAE]",
    textColor: "text-[#FEFEFA]",
    hex: "#6B8CAE",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "gene", label: "Gene", type: "text" },
      { key: "variant", label: "Variant / SNP", type: "text" },
      { key: "clinical_significance", label: "Clinical Significance", type: "textarea" },
      { key: "related_conditions", label: "Related Conditions", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "lab_tests",
    label: "Lab Test",
    labelPlural: "Lab Tests",
    color: "bg-[#468189]",
    textColor: "text-[#FEFEFA]",
    hex: "#468189",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "what_it_measures", label: "What It Measures", type: "textarea" },
      { key: "indications", label: "Indications", type: "textarea" },
      { key: "ranges", label: "Ranges", type: "textarea" },
      { key: "source", label: "Source", type: "entity_source", sourceEntityTypes: ["laboratories", "vendors"] },
      { key: "collection_type", label: "Collection Type", type: "text" },
      { key: "cost", label: "Cost", type: "text" },
      { key: "instructions", label: "Instructions", type: "textarea" },
      { key: "faqs", label: "FAQs", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "laboratories",
    label: "Laboratory",
    labelPlural: "Laboratories",
    color: "bg-[#5B8FA8]",
    textColor: "text-[#FEFEFA]",
    hex: "#5B8FA8",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "website", label: "Website", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "address", label: "Address", type: "text" },
      { key: "specialties", label: "Specialties", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "medications",
    label: "Medication",
    labelPlural: "Medications",
    color: "bg-[#031926]",
    textColor: "text-[#FEFEFA]",
    hex: "#031926",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "prescription", label: "Prescription (Rx)", type: "text" },
      { key: "drug_class", label: "Drug Class", type: "text" },
      { key: "dosage", label: "Dosage", type: "text" },
      { key: "cost", label: "Cost", type: "text" },
      { key: "mechanism_of_action", label: "Mechanism of Action", type: "textarea" },
      { key: "side_effects", label: "Side Effects", type: "textarea" },
      { key: "contraindications", label: "Contraindications", type: "textarea" },
      { key: "interactions", label: "Interactions", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "nutrition",
    label: "Nutrition",
    labelPlural: "Nutrition",
    color: "bg-[#6B9E6B]",
    textColor: "text-[#FEFEFA]",
    hex: "#6B9E6B",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "nutrient_class", label: "Nutrient Class", type: "text" },
      { key: "food_sources", label: "Food Sources", type: "textarea" },
      { key: "functions", label: "Functions", type: "textarea" },
      { key: "deficiency_signs", label: "Deficiency Signs", type: "textarea" },
      { key: "excess_signs", label: "Excess / Toxicity Signs", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "products",
    label: "Product",
    labelPlural: "Products",
    color: "bg-[#C87941]",
    textColor: "text-[#FEFEFA]",
    hex: "#C87941",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "brand", label: "Brand", type: "text" },
      { key: "product_type", label: "Product Type", type: "text" },
      { key: "where_to_buy", label: "Where to Buy", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "protocols",
    label: "Protocol",
    labelPlural: "Protocols",
    color: "bg-[#77ACA2]",
    textColor: "text-[#272727]",
    hex: "#77ACA2",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "steps", label: "Steps", type: "textarea" },
      { key: "formula", label: "Formula", type: "textarea" },
      { key: "duration", label: "Duration", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "supplements",
    label: "Supplement",
    labelPlural: "Supplements",
    color: "bg-[#F4E9CD]",
    textColor: "text-[#272727]",
    hex: "#F4E9CD",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "indications", label: "Indications", type: "textarea" },
      { key: "mechanism_of_action", label: "Mechanism of Action", type: "textarea" },
      { key: "dosage", label: "Dosage", type: "text" },
      { key: "forms", label: "Forms", type: "array" },
      { key: "recommended_brands", label: "Recommended Brands", type: "textarea" },
      { key: "when_to_take", label: "When to Take", type: "text" },
      { key: "how_long_to_take", label: "How Long to Take", type: "text" },
      { key: "prn_usage", label: "PRN Usage", type: "textarea" },
      { key: "adverse_effects", label: "Adverse Effects", type: "textarea" },
      { key: "contraindications", label: "Contraindications", type: "textarea" },
      { key: "ingredients", label: "Ingredients", type: "textarea" },
      { key: "source", label: "Source (Where to Order)", type: "textarea" },
      { key: "testing", label: "Testing", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "symptoms",
    label: "Symptom",
    labelPlural: "Symptoms",
    color: "bg-[#9DBEBB]",
    textColor: "text-[#272727]",
    hex: "#9DBEBB",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "related_biochemistry", label: "Related Biochemistry", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    type: "vendors",
    label: "Vendor / Pharmacy",
    labelPlural: "Vendors & Pharmacies",
    color: "bg-[#9DBEBB]",
    textColor: "text-[#272727]",
    hex: "#9DBEBB",
    fields: [
      { key: "description", label: "Description", type: "textarea" },
      { key: "website", label: "Website", type: "text" },
      { key: "vendor_type", label: "Type", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
];

export const ENTITY_TYPES = ENTITY_CONFIGS.map((e) => e.type);

export function getEntityConfig(type: string): EntityConfig | undefined {
  return ENTITY_CONFIGS.find((e) => e.type === type);
}
